import { randomInt } from 'crypto';

export const SEEDED_DEBATE_TOPICS = [
  'This house would ban homework in secondary schools.',
  'This house supports a four-day school week.',
  'This house would make university education free.',
  'This house would require financial literacy in schools.',
  'This house would replace grades with narrative feedback.',
  'This house supports school uniforms.',
  'This house would ban smartphones in classrooms.',
  'This house would prioritize vocational training over university expansion.',
  'This house would require public speaking courses for all students.',
  'This house would allow students to evaluate teachers publicly.',
  'This house believes AI tutors improve educational equality.',
  'This house would limit standardized testing.',
  'This house would require climate education in all schools.',
  'This house would make coding a core subject.',
  'This house would ban private tutoring companies.',
  'This house would lower the voting age to 16.',
  'This house supports mandatory voting.',
  'This house would use online voting in national elections.',
  'This house would cap campaign spending.',
  'This house would ban political advertising on social media.',
  'This house supports proportional representation.',
  'This house would require politicians to publish tax returns.',
  'This house would introduce term limits for legislators.',
  'This house would allow citizens to recall elected officials.',
  'This house believes local governments should control more tax revenue.',
  'This house would regulate social media algorithms.',
  'This house would ban facial recognition in public spaces.',
  'This house supports stronger data privacy laws.',
  'This house would make tech companies liable for harmful content.',
  'This house believes children under 16 should not use social media.',
  'This house would require AI-generated content labels.',
  'This house would tax automation that replaces workers.',
  'This house supports open-source software in government.',
  'This house would ban targeted advertising to minors.',
  'This house believes remote work should be a legal right where possible.',
  'This house would introduce universal basic income.',
  'This house supports a higher minimum wage.',
  'This house would tax wealth more heavily than income.',
  'This house would cap executive pay.',
  'This house believes governments should prioritize inflation over unemployment.',
  'This house would ban unpaid internships.',
  'This house supports rent control in major cities.',
  'This house would break up large monopolies.',
  'This house would require companies to publish salary ranges.',
  'This house supports shorter working hours with no pay cut.',
  'This house would ban single-use plastics.',
  'This house supports nuclear power as part of climate policy.',
  'This house would tax frequent flyers.',
  'This house would require vegetarian meals in public institutions.',
  'This house would ban new fossil fuel exploration.',
  'This house supports carbon tariffs on imported goods.',
  'This house would make public transport free.',
  'This house would protect 30 percent of land and oceans.',
  'This house believes climate activists should use civil disobedience.',
  'This house would require companies to disclose climate risks.',
  'This house would legalize assisted dying.',
  'This house would ban cosmetic animal testing.',
  'This house supports mandatory vaccination for public school attendance.',
  'This house would prioritize preventive healthcare funding.',
  'This house would ban the sale of tobacco to future generations.',
  'This house supports sugar taxes.',
  'This house would make mental health days mandatory at work.',
  'This house would decriminalize drug possession.',
  'This house would require organ donation by default unless people opt out.',
  'This house believes healthcare should be publicly funded.',
  'This house would abolish the death penalty.',
  'This house supports restorative justice over prison for minor crimes.',
  'This house would ban private prisons.',
  'This house would allow cameras in all courtrooms.',
  'This house would use AI risk tools in sentencing.',
  'This house would lower penalties for nonviolent drug offenses.',
  'This house supports community service instead of short prison sentences.',
  'This house would make police body cameras mandatory.',
  'This house would abolish cash bail.',
  'This house believes hate speech should be legally restricted.',
  'This house would require national service for young adults.',
  'This house supports open borders for refugees.',
  'This house would prioritize skilled immigration.',
  'This house would sanction countries that violate human rights.',
  'This house supports humanitarian intervention without UN approval.',
  'This house would reduce military spending.',
  'This house believes global institutions should have more power.',
  'This house would cancel debt for developing countries.',
  'This house supports fair trade over free trade.',
  'This house would ban arms sales to authoritarian regimes.',
  'This house would regulate influencer marketing.',
  'This house would ban beauty filters in ads.',
  'This house supports gender quotas in corporate leadership.',
  'This house would pay parents for caregiving work.',
  'This house believes celebrities should avoid political endorsements.',
  'This house would require equal prize money in all sports.',
  'This house would ban gambling ads during sports broadcasts.',
  'This house supports public funding for the arts.',
  'This house would remove anonymous accounts from major platforms.',
  'This house believes cancel culture does more harm than good.',
  'This house would grant legal rights to nature.',
  'This house supports lab-grown meat.',
  'This house would ban deepfake pornography.',
  'This house believes space exploration deserves public funding.',
  'This house would require companies to use ethical supply chains.',
] as const;

export function getRandomSeededDebateTopic() {
  return SEEDED_DEBATE_TOPICS[randomInt(SEEDED_DEBATE_TOPICS.length)];
}
